-- MySQL Script generated by MySQL Workbench
-- Fri Mar  6 08:42:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_ECommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_ECommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_ECommerce` DEFAULT CHARACTER SET utf8 ;
USE `BD_ECommerce` ;

-- -----------------------------------------------------
-- Table `BD_ECommerce`.`ArticleTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`ArticleTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Artists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Artists_Countries1_idx` (`country_id` ASC),
  CONSTRAINT `fk_Artists_Countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `BD_ECommerce`.`Countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Labels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`VinyleFormats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`VinyleFormats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `releaseYear` SMALLINT(4) NOT NULL,
  `pathFileCover` VARCHAR(80) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `quantity` SMALLINT(5) NOT NULL,
  `articleType_id` INT NOT NULL,
  `artist_id` INT NOT NULL,
  `label_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  `vinyleFormat_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Articles_ArticleType_idx` (`articleType_id` ASC),
  INDEX `fk_Articles_Artists1_idx` (`artist_id` ASC),
  INDEX `fk_Articles_Labels1_idx` (`label_id` ASC),
  INDEX `fk_Articles_Genres1_idx` (`genre_id` ASC),
  INDEX `fk_Articles_Formats1_idx` (`vinyleFormat_id` ASC),
  CONSTRAINT `fk_Articles_ArticleType`
    FOREIGN KEY (`articleType_id`)
    REFERENCES `BD_ECommerce`.`ArticleTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_Artists1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `BD_ECommerce`.`Artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_Labels1`
    FOREIGN KEY (`label_id`)
    REFERENCES `BD_ECommerce`.`Labels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_Genres1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `BD_ECommerce`.`Genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_Formats1`
    FOREIGN KEY (`vinyleFormat_id`)
    REFERENCES `BD_ECommerce`.`VinyleFormats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Musics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Musics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `pathFileMusic` VARCHAR(80) NOT NULL,
  `duration` VARCHAR(5) NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Musics_Articles1_idx` (`article_id` ASC),
  CONSTRAINT `fk_Musics_Articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `BD_ECommerce`.`Articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(35) NOT NULL,
  `zip` SMALLINT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(35) NOT NULL,
  `firstname` VARCHAR(35) NOT NULL,
  `address` VARCHAR(40) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customers_Cities1_idx` (`city_id` ASC),
  CONSTRAINT `fk_Customers_Cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `BD_ECommerce`.`Cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `orderDate` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orders_Customers1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `BD_ECommerce`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Administrators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Artists_has_Musics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Artists_has_Musics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `artist_id` INT NOT NULL,
  `music_id` INT NOT NULL,
  INDEX `fk_Artists_has_Musics_Musics1_idx` (`music_id` ASC),
  INDEX `fk_Artists_has_Musics_Artists1_idx` (`artist_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Artists_has_Musics_Artists1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `BD_ECommerce`.`Artists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artists_has_Musics_Musics1`
    FOREIGN KEY (`music_id`)
    REFERENCES `BD_ECommerce`.`Musics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_ECommerce`.`Orders_has_Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_ECommerce`.`Orders_has_Articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orders_id` INT NOT NULL,
  `articles_id` INT NOT NULL,
  `quantity` SMALLINT(3) NOT NULL,
  INDEX `fk_Orders_has_Articles_Articles1_idx` (`articles_id` ASC),
  INDEX `fk_Orders_has_Articles_Orders1_idx` (`orders_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Orders_has_Articles_Orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `BD_ECommerce`.`Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_has_Articles_Articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `BD_ECommerce`.`Articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
